/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.escuela;

import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author arman
 */
public class VizualizarDatos extends javax.swing.JFrame {
    
    
    /**
     * Creates new form VizualizarDatos
     */
    public VizualizarDatos() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Caracter = new javax.swing.JButton();
        ImagenBytes = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        AreaCaracter = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextImagen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Caracter.setText("Caracteres");
        Caracter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaracterActionPerformed(evt);
            }
        });

        ImagenBytes.setText("Imagen");
        ImagenBytes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImagenBytesActionPerformed(evt);
            }
        });

        AreaCaracter.setColumns(20);
        AreaCaracter.setRows(5);
        jScrollPane3.setViewportView(AreaCaracter);

        jTextImagen.setColumns(20);
        jTextImagen.setRows(5);
        jScrollPane4.setViewportView(jTextImagen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(Caracter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagenBytes)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caracter)
                    .addComponent(ImagenBytes))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagenBytesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagenBytesActionPerformed

        try {
            FileReader fr = new FileReader("imagen.txt"); 
            int data; 
            int j = 0; 
            char[] array = new char[100];
            while((data=fr.read()) != -1)
            {
                if((char)data == '\\'){
                    System.out.println("barra");
                    array[j] = '/';
                    j++;
                   
                }else
                {
                    
                    array[j] = (char)data;
                    j++; 
                }
                
                
            }
            String str = new String(array);
            fr.close();
            System.out.print(str);
            
            File archivo = new File("sample.jpg");
            byte[] imgFoto = new byte[(int)archivo.length()];
            InputStream inte;
            inte = new FileInputStream(archivo);
            inte.read(imgFoto);
            jTextImagen.append(new String(imgFoto));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VizualizarDatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VizualizarDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_ImagenBytesActionPerformed

    private void CaracterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaracterActionPerformed
        try {
            FileReader fr;   
            fr = new FileReader("archivo.txt");
            int i;   
            char[] array = new char[100];
            int j= 0;
            while((i=fr.read())!=-1) {
                array[j] = (char)i;
                j++;
                System.out.print((char)i);
            }
            String str = new String(array);
            AreaCaracter.setText(str);
            fr.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VizualizarDatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VizualizarDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_CaracterActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaCaracter;
    private javax.swing.JButton Caracter;
    private javax.swing.JButton ImagenBytes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextImagen;
    // End of variables declaration//GEN-END:variables
}
